spring:
  application:
    name: libraryapi
  # DATASOURCE
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:libraryapi
    username: sa
    password:
  # H2 CLIENT
  h2:
    console:
      enabled: true
      path: /h2-console
  # JPA, SQL
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

logging:
  file:
    name: libraryApi.log

springdoc:
  override-with-generic-response: false